export const CONSTANTS = {
    // Pagnition
    ITEM_PER_PAGE: 5,
    // Login
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOG_OUT: 'LOG_OUT',
    // Expense
    ADD_EXPENSE: 'ADD_EXPENSE',
    CHANGE_EXPENSE_FORM: 'CHANGE_EXPENSE_FORM',
    CLOSE_FROM: 'CLOSE_FROM',
    GET_EDIT_EXPENSE_DATA: 'GET_EDIT_EXPENSE_DATA',
    DELETE_EXPENSE_DATA: 'DELETE_EXPENSE_DATA',
    // Monthly Earning
    ADD_MONTHLY_EARNING: 'ADD_MONTHLY_EARNING',
    CHANGE_EARNING_FORM: 'CHANGE_EARNING_FORM',
    GET_EDIT_MONTHLY_EARNING_DATA: 'GET_EDIT_MONTHLY_EARNING_DATA',
    DELETE_MONTHLY_EARNING: 'DELETE_MONTHLY_EARNING',
}