export const CONSTANTS = {
    ADD_EXPENSE: 'ADD_EXPENSE',
    CHANGE_EXPENSE_FORM: 'CHANGE_EXPENSE_FORM',
    CLOSE_FROM: 'CLOSE_FROM',
    GET_EDIT_EXPENSE_DATA: 'GET_EDIT_EXPENSE_DATA',
    DELETE_EXPENSE_DATA: 'DELETE_EXPENSE_DATA',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOG_OUT: 'LOG_OUT'
}